export const styles = {
  appContainer: {
    display: 'flex',
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 50%, #ffffff 100%)',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
  },
  mainContent: {
    flex: 1,
    transition: 'margin-left 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    marginLeft: '280px',
    width: 'calc(100% - 280px)',
  },
  contentArea: {
    padding: '24px 32px',
  },
  panelContainer: {
    display: 'block',
  },
  sidebar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '280px',
    height: '100vh',
    background: 'rgba(255, 255, 255, 0.75)',
    backdropFilter: 'blur(20px)',
    borderRight: '1px solid rgba(255, 255, 255, 0.4)',
    boxShadow: '20px 0 40px rgba(0,0,0,0.05), -5px 0 15px rgba(0,0,0,0.02)',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 200,
    transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    transform: 'translateX(0)',
  },
  sidebarHeader: {
    padding: '28px 20px 20px 24px',
    borderBottom: '1px solid rgba(0,0,0,0.05)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sidebarToggle: {
    background: 'rgba(0,0,0,0.05)',
    border: 'none',
    borderRadius: '12px',
    padding: '6px 10px',
    cursor: 'pointer',
    fontSize: 12,
    color: '#64748b',
    transition: 'all 0.2s',
  },
  sidebarNav: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px 16px',
  },
  sidebarFooter: {
    padding: '20px',
    borderTop: '1px solid rgba(0,0,0,0.05)',
  },
  logo3d: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    position: 'relative',
  },
  logoGlow: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    background: 'radial-gradient(circle at 30% 20%, rgba(37,99,235,0.2), transparent 70%)',
    filter: 'blur(12px)',
    zIndex: -1,
  },
  logoIcon: {
    fontSize: 32,
    filter: 'drop-shadow(0 4px 6px rgba(0,0,0,0.1))',
  },
  logoName: {
    fontSize: 18,
    fontWeight: 800,
    background: 'linear-gradient(135deg, #1e293b, #3b82f6)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  logoSub: {
    fontSize: 10,
    fontWeight: 600,
    color: '#94a3b8',
    letterSpacing: '1px',
  },
  menuGroup: {
    marginBottom: 28,
  },
  menuGroupTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '1px',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginBottom: 12,
    paddingLeft: 12,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  menuGroupIcon: {
    fontSize: 14,
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    width: '100%',
    padding: '12px 16px',
    marginBottom: 4,
    background: 'transparent',
    border: 'none',
    borderRadius: '16px',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    color: '#475569',
    transition: 'all 0.2s ease',
    position: 'relative',
  },
  menuItemActive: {
    background: 'linear-gradient(135deg, rgba(37,99,235,0.12), rgba(124,58,237,0.08))',
    color: '#2563eb',
    fontWeight: 600,
    boxShadow: 'inset 0 1px 1px rgba(255,255,255,0.4), 0 2px 6px rgba(0,0,0,0.02)',
  },
  menuItemHover: {
    background: 'rgba(0,0,0,0.02)',
    transform: 'translateX(4px)',
  },
  menuItemIcon: {
    fontSize: 20,
    width: 28,
  },
  menuItemLabel: {
    flex: 1,
    textAlign: 'left',
  },
  activeIndicator: {
    position: 'absolute',
    right: 12,
    width: 6,
    height: 6,
    background: '#3b82f6',
    borderRadius: '50%',
    boxShadow: '0 0 0 2px rgba(59,130,246,0.3)',
  },
  userCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    background: 'rgba(255,255,255,0.5)',
    backdropFilter: 'blur(8px)',
    borderRadius: '20px',
    padding: '12px 16px',
    border: '1px solid rgba(255,255,255,0.6)',
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: '20px',
    background: 'linear-gradient(135deg, #3b82f6, #7c3aed)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 700,
    fontSize: 18,
    boxShadow: '0 4px 10px rgba(59,130,246,0.3)',
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 14,
    fontWeight: 700,
    color: '#1e293b',
  },
  userRole: {
    fontSize: 10,
    color: '#64748b',
    fontWeight: 500,
  },
  logoutBtn: {
    background: 'rgba(0,0,0,0.05)',
    border: 'none',
    borderRadius: '12px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontSize: 16,
    transition: 'all 0.2s',
  },
  topBar: {
    position: 'sticky',
    top: 0,
    background: 'rgba(255,255,255,0.7)',
    backdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(255,255,255,0.4)',
    padding: '12px 32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 100,
  },
  topBarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 20,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: 'rgba(241,245,249,0.6)',
    borderRadius: '40px',
    padding: '6px 16px',
    border: '1px solid rgba(0,0,0,0.05)',
  },
  notificationBell: {
    position: 'relative',
    fontSize: 20,
    cursor: 'pointer',
  },
  notificationBadge: {
    position: 'absolute',
    top: -6,
    right: -8,
    background: '#ef4444',
    color: '#fff',
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 6px',
    borderRadius: '20px',
  },
  topUserBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    background: 'rgba(0,0,0,0.04)',
    padding: '6px 16px 6px 12px',
    borderRadius: '40px',
    cursor: 'pointer',
  },
  topAvatar: {
    width: 32,
    height: 32,
    borderRadius: '16px',
    background: 'linear-gradient(135deg, #3b82f6, #7c3aed)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 700,
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 28,
    flexWrap: 'wrap',
    gap: 16,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: 800,
    background: 'linear-gradient(135deg, #1e293b, #334155)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    margin: 0,
    lineHeight: 1.2,
  },
  pageSubtitle: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 6,
  },
  dateBadge: {
    background: 'rgba(255,255,255,0.6)',
    backdropFilter: 'blur(8px)',
    padding: '8px 18px',
    borderRadius: '40px',
    fontSize: 13,
    fontWeight: 500,
    color: '#475569',
    border: '1px solid rgba(255,255,255,0.8)',
  },
  hamburger: {
    background: 'rgba(0,0,0,0.04)',
    border: 'none',
    fontSize: 20,
    padding: '8px 14px',
    borderRadius: '30px',
    cursor: 'pointer',
    display: 'none',
    color: '#475569',
  },
glassCard: {
    background: 'rgba(255,255,255,.75)',
    backdropFilter: 'blur(16px)',

    position: 'relative',
    zIndex: 1,
    overflow: 'visible',

    borderRadius: 28,
    padding: 24,
    marginBottom: 24,
},
  badge: {
    background: 'rgba(37,99,235,0.12)',
    color: '#2563eb',
    padding: '5px 14px',
    borderRadius: '40px',
    fontSize: 12,
    fontWeight: 600,
    backdropFilter: 'blur(4px)',
  },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 },
  input: { 
    padding: '10px 14px', 
    border: '1px solid rgba(0,0,0,0.08)', 
    borderRadius: 16, 
    fontSize: 13, 
    fontFamily: 'inherit', 
    background: 'rgba(255,255,255,0.8)', 
    width: '100%', 
    boxSizing: 'border-box', 
    transition: 'all 0.2s' 
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: { 
    textAlign: 'left', 
    padding: '12px 16px', 
    background: 'rgba(241,245,249,0.5)', 
    fontSize: 12, 
    fontWeight: 700, 
    color: '#475569', 
    borderBottom: '1px solid rgba(0,0,0,0.05)' 
  },
  td: { 
    padding: '12px 16px', 
    borderBottom: '1px solid rgba(0,0,0,0.05)', 
    fontSize: 13, 
    verticalAlign: 'middle' 
  },
  
  emptyTd: { textAlign: 'center', padding: '32px', color: '#94a3b8', fontSize: 13 },
  btnPrimary: { 
    padding: '10px 18px', 
    borderRadius: 40, 
    border: 'none', 
    fontWeight: 600, 
    cursor: 'pointer', 
    fontSize: 13, 
    background: 'linear-gradient(135deg, #2563eb, #7c3aed)', 
    color: '#fff', 
    display: 'inline-flex', 
    alignItems: 'center', 
    gap: 8, 
    boxShadow: '0 2px 8px rgba(59,130,246,0.3)', 
    transition: 'transform 0.1s, box-shadow 0.1s' 
  },
  btnOutline: { 
    padding: '10px 18px', 
    borderRadius: 40, 
    border: '1px solid rgba(0,0,0,0.1)', 
    fontWeight: 600, 
    cursor: 'pointer', 
    fontSize: 13, 
    background: 'rgba(255,255,255,0.6)', 
    color: '#475569', 
    backdropFilter: 'blur(4px)' 
  },
  btnDanger: { 
    padding: '6px 12px', 
    borderRadius: 30, 
    border: 'none', 
    fontWeight: 600, 
    cursor: 'pointer', 
    fontSize: 12, 
    background: '#fee2e2', 
    color: '#dc2626' 
  },
  modalOverlay: { 
    position: 'fixed', 
    inset: 0, 
    background: 'rgba(0,0,0,.4)', 
    backdropFilter: 'blur(8px)', 
    zIndex: 500, 
    display: 'flex', 
    alignItems: 'center', 
    justifyContent: 'center', 
    padding: 16 
  },
  modal: { 
    background: '#fff', 
    borderRadius: 32, 
    padding: 28, 
    width: '100%', 
    maxWidth: 900, 
    maxHeight: '90vh', 
    overflowY: 'auto' 
  },
  histItem: { 
    background: 'rgba(248,250,252,0.8)', 
    backdropFilter: 'blur(4px)', 
    border: '1px solid rgba(0,0,0,0.05)', 
    borderRadius: 16, 
    padding: 14, 
    marginBottom: 12, 
    cursor: 'pointer', 
    transition: 'all .15s' 
  },
  badgeBlue: { 
    background: '#dbeafe', 
    color: '#1d4ed8', 
    padding: '3px 10px', 
    borderRadius: 20, 
    fontSize: 11, 
    fontWeight: 700 
  },
  btnSm: { 
    padding: '6px 12px', 
    background: 'transparent', 
    border: '1px solid #e2e8f0', 
    borderRadius: 8, 
    fontSize: 12, 
    fontWeight: 600, 
    cursor: 'pointer', 
    color: '#64748b' 
  },
  modalHeader: { 
    display: 'flex', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    padding: '0 0 16px 0', 
    borderBottom: '1px solid #e2e8f0' 
  },
  modalTitle: { 
    fontSize: 18, 
    fontWeight: 700, 
    color: '#0f172a' 
  },
  modalClose: { 
    background: 'none', 
    border: 'none', 
    fontSize: 20, 
    cursor: 'pointer', 
    color: '#94a3b8' 
  },
  modalBody: { 
    padding: '20px 0' 
  },
  modalFooter: { 
    display: 'flex', 
    justifyContent: 'flex-end', 
    gap: 10, 
    paddingTop: 16, 
    borderTop: '1px solid #e2e8f0' 
  },
  formGrid2: { 
    display: 'grid', 
    gridTemplateColumns: '1fr 1fr', 
    gap: 14 
  },
  suggBox: { 
    position: 'absolute', 
    top: '100%', 
    left: 0, 
    right: 0, 
    background: 'rgba(255,255,255,0.98)', 
    backdropFilter: 'blur(16px)', 
    border: '1px solid rgba(0,0,0,0.08)', 
    borderRadius: 16, 
    maxHeight: 280, 
    overflowY: 'auto', 
    zIndex: 200, 
    boxShadow: '0 12px 28px rgba(0,0,0,0.1)' 
  },
  suggItem: { 
    padding: '10px 16px', 
    cursor: 'pointer', 
    borderBottom: '1px solid #f1f5f9' 
  },
 suggTableBox: {
    position: 'relative',
    top: 'calc(100% + 5px)',
    left: 0,
    right: 0,
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 16,
    maxHeight: 400,
    overflowY: 'auto',
    boxShadow: '0 12px 28px rgba(0,0,0,.12)',
    zIndex: 999999,
    marginTop: 0,
},
  suggTable: { 
    width: '100%', 
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
  },
  suggTableHeader: { 
    background: '#f8fafc', 
    position: 'sticky', 
    top: 0, 
    zIndex: 2,
    borderBottom: '2px solid #e2e8f0',
  },
  suggTableTh: { 
    padding: '8px 12px', 
    textAlign: 'left', 
    fontSize: 11, 
    fontWeight: 700, 
    color: '#475569', 
    borderBottom: '1px solid #e2e8f0',
    background: '#f8fafc',
    whiteSpace: 'nowrap',
  },
  suggTableRow: { 
    cursor: 'pointer', 
    transition: 'background 0.15s',
    borderBottom: '1px solid #f1f5f9',
  },
  suggTableTd: { 
    padding: '8px 12px', 
    fontSize: 13, 
    verticalAlign: 'middle',
    borderBottom: '1px solid #f1f5f9',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  suggCreate: { 
    padding: '12px', 
    textAlign: 'center', 
    background: '#d1fae5', 
    color: '#065f46', 
    fontWeight: 600, 
    cursor: 'pointer', 
    borderRadius: '0 0 16px 16px',
    borderTop: '1px solid #a7f3d0',
    position: 'sticky',
    bottom: 0,
    zIndex: 2,
  },
  suggAddBtn: { 
    padding: '4px 12px', 
    background: 'linear-gradient(135deg, #2563eb, #3b82f6)', 
    color: '#fff', 
    border: 'none', 
    borderRadius: 20, 
    fontSize: 12, 
    fontWeight: 600, 
    cursor: 'pointer' 
  },
};